### DISCUSSION TITLE
how to make bot empty bin after each room?

### DISCUSSION THREAD

**Discussion by TRusselo** [Tasshack/dreame-vacuum#134] [General]
is there a way to script, or have the robot empty its bin at the dock after each room?

my upper floor has 3 bedrooms, they have carpet.  we have 2 dogs, and one sheds his undercoat twice a year.....
needless to say no robot can survive my whole upstairs in one shot.

today it was packed full after 2 rooms, was lucky the battery wore out before it did the third... 
it did NOT auto empty.  i manually did it while playing.

the app only has option for auto-empty after each completed task, or after 2 / 3  completed tasks... oof.

i need it to empty every 0.5 tasks. LOL   or 0.333333

**Comment by TRusselo** [comment]
i guess maybe script:

-clean room1 (task 1)
-wait 20 min
-clean room2 (task 2)
-wait 20 min
-clean room3 (task 3)
ect

but i bet someone smarter has a better idea?

**Comment by Tasshack** [comment]
Robot will always return to the dock after a cleaning job is finished and your script should look like;

1. Send command to only clean room 1
2. Wait for robot to return to the dock
3. Send command to only clean room 2
4. Wait for robot to return to the dock
5. Send command to only clean room 3
6. Wait for robot to return to the dock
.
.
.

**Comment by TRusselo** [comment]
I would love an example of code:

My current attempts do nothing.
```
alias: Clean 1 Room
sequence:
  - service: dreame_vacuum.vacuum_set_custom_cleaning
    data:
      segment_id: 6
      suction_level: 4
      repeats: 1
      water_volume: 1
    target:
      entity_id: vacuum.bitch_vac
mode: single
```
