### DISCUSSION TITLE
Segments for vacuum_clean_segment call

### DISCUSSION THREAD

**Discussion by dailow** [Tasshack/dreame-vacuum#312] [Q&A] [answered]
I noticed when using the vacuum_clean_segment, only one segment is it highlighted when looking at the Dreame app.  Is this expected?  Only segment 18 is highlighted in the app.  Does 19 get called afterwards?

This is what the call looks like.

```
service: dreame_vacuum.vacuum_clean_segment
data:
  segments:
    - 18
    - 19
  suction_level: 3
  water_volume: 3
  repeats: 2
target:
  entity_id: vacuum.dreamebot_l20_ultra
enabled: true
```
