### DISCUSSION TITLE
The problem with cleaning the segment via HA

### DISCUSSION THREAD

**Discussion by sergey-1976** [Tasshack/dreame-vacuum#359] [Q&A] [answered]
Hi.

I have high thresholds between rooms and the vacuum cleaner can't immediately get on them.
If I send a segment from the native MiHome application to clean, the vacuum cleaner tries to cross the threshold several times and eventually drives in and cleans the selected room. 
If I send the vacuum cleaner to clean up the selected segment with a script from HA, then the vacuum cleaner tries to enter 1-2 times, it fails and it returns to the base.

Script:

```
alias: clean_segment_3
sequence:
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      segments: 3
      repeats: 1
      suction_level: 1
    target:
      area_id: home
mode: single
```
