### DISCUSSION TITLE
How to start a segment cleaning from iobroker?

### DISCUSSION THREAD

**Discussion by pardofelis** [Tasshack/dreame-vacuum#379] [General]
Hi folks, hi Tasshack,

first of all: Thank you for the incredible work you have done with this plugin for Home Assistant.
I am very happy that I found this neat plugin - especially as there is no possibility to control my Dreame vacuum robot directly with an adapter in iobroker.

Using the "hass"-adapter, I have meanwhile managed to get the states of Home Assistant into iobroker.
Now my question: Does anyone use this plugin and has managed to start a "segment cleaning" from inside iobroker? I thought, that there might be a way to run the service from iobroker or to use "send_command" to send the segments directly to the robot. But sadly, I wasn't successful. 

If anyone has managed that and is willing to share how it is done, I am very thankful.

Sincerely pardofelis

**Comment by pardofelis** [comment]
After a long time of try and mostly error, I came up with a first solution:
As a first way to solve it, I did following:
**If anyone has a better solution, I am happy to hear of it.**

And if the following is obvious to a HomeAssistant User, I am sorry, but it wasn't obvious to me as I switched from Home Assistent to iobroker because I didn't understand it...

To do in **Home Assistant**
1. Add a helper state (settings>devices>helper>create helper>text) e.g. with the name "cleansegments"
2. Automatisation
2.1 Add an automatisation (settings>automatisations>add automatisation>new automatisation)
2.2 Now switch to YAML-Editor mode (using the three vertical dots in top right edge)
2.3 Enter the following text:

```
alias: Trigger Vacuum Clean Segment Service
description: ""
trigger:
  - platform: state
    entity_id:
      - input_text.cleansegments
    from: null
    to: null
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition: []
action:
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      segments: "{{states('input_text.cleansegments')}}"
      repeats: 1
      entity_id: vacuum.######
mode: single

```
2.4 In the spot of "#####" enter the entity_id of your vacuum cleaner - and if necessary, rename the name of the state  twice in the code, if you have given it a different name than cleansegments

**iobroker**
1. install module hass and set the instance up
2. if you have already had it before you set up the text-state in home assistent, restart the hass-instance to see the state.
3. To start a segment cleaning, write the number of the room/rooms into the text-state (e.g. [1] for segment 1  or [2,4] for segments 2 and 4)
