### DISCUSSION TITLE
Overwrite cleaning mode during zone cleanup

### DISCUSSION THREAD

**Discussion by dtretyakov** [Tasshack/dreame-vacuum#478] [General]
I'm not sure whether it's possible, but it would be great to have a possibility to set custom `cleaning_mode` in the `vacuum_clean_zone`/`vacuum_clean_segment` service calls.

**Comment by Tasshack** [comment]
`It would be great` is not enough for me to make this change. You need to explain why you need this service call when it won't affect anything with the operation of the zone cleaning.

**Reply by dtretyakov** [reply]
The use case is simple:
If by default the vacuum is set to "Sweeping and mopping" and on some events you need to trigger zone cleanup in "Sweeping" mode this make it possible easily implement that.

**Reply by Tasshack** [reply]
```
service: select.select_option
target:
  entity_id: select.vacuum_cleaning_mode
data:
  option: sweeping
```
