### DISCUSSION TITLE
Why is the suction level not available for clean zone action?

### DISCUSSION THREAD

**Discussion by DeckardCain2014** [Tasshack/dreame-vacuum#668] [Q&A] [answered]
Hi,
I have the following script for cleaning specific zones in one action. 
I noticed the suction level is not configurable for that. Why is that? I would like to select it for this specific action
```
alias: Kloreinigung
sequence:
  - target:
      entity_id: vacuum.moppie
    data:
      zone:
        - - 4427
          - 478
          - 7593
          - 2105
        - - 7673
          - 950
          - 9688
          - 1663
        - - 3100
          - 897
          - 5209
          - 5298
        - - 5136
          - 4381
          - 7557
          - 5629
        - - 6601
          - 939
          - 7552
          - 4323
      repeats: 1
      suction_level: 3
    action: dreame_vacuum.vacuum_clean_zone
mode: single
icon: mdi:toilet

```
