### DISCUSSION TITLE
Base Station Cleaning / Washboard cleaning button

### DISCUSSION THREAD

**Discussion by riboyama** [Tasshack/dreame-vacuum#715] [Ideas]
The L10s pro ultra heat (and I think the X40) don't have buttons on the dock to dispense/drain water manually.
The app has a "Base Station Cleaning" button which dispenses water onto the washboard base and then after 20s drains it.

I checked the miio logs on the device and you can use this HASS action to do it, but a button like the 'Base station self repair' would be a nice feature:
```
action: vacuum.send_command
data:
  command: action
  params:
    siid: 4
    aiid: 4
    in: [{"value":"5,1","piid":10}]
```
