### DISCUSSION TITLE
Conditional no-go zone/virtual wall based on sensor

### DISCUSSION THREAD

**Discussion by Chaoscontrol** [Tasshack/dreame-vacuum#958] [Q&A] [answered]
I have a small step separating my living room and my office. See image (for some reason these last days the map has twisted itself). 

![image](https://github.com/user-attachments/assets/51318345-c5bb-43f6-8cfa-30fa4f622bdc)

I have a virtual wall in there to separate the 2 so my D10 Plus doesn't jump down. But I have 3D printed a slope in an attempt to automate cleaning the office too. The slope works fine and I've adjusted the virtual wall to allow the gap as you can see. 

However, even when I tell to clean just the Living room, it interprets the gap as a threshold, so it gets a bit in, and sometimes it falls. 

So basically I'd like to add a door sensor to the slope, so that when it's in position, the robot can go down and clean the office. But if it's not, to add a no-go zone slightly thicker so that it doesn't get as close to the step. 

The logic is obviously down to HA automation. But my question here is to know how to set up that "saved zone" that I can enable/disable via some automation action. 

Thanks!

**Comment by Tasshack** [comment]
You can save your virtual walls inside of an automation and add/remove them using the `set_restricted_zone` service.

**Reply by Chaoscontrol** [reply]
Thanks, I'll play with that. How is a wall defined though? According to the docs, a wall has 4 points just like a zone. Shouldn't it have 2 points?

And I understand these zones won't show in the app? Or your suggestion is to create and delete this one using the coordinates every time I need?

Finally, won't these numbers "change" with every clean/scan the robovac does? Just saying because I noticed my map twisting lately, so not sure how the zone reacts to that.

**Comment by Chaoscontrol** [comment, marked as answer]
In case it's useful for someone, here it is:

The restricted zones get saved whenever a new one is set. So you need to save those coordinates to reapply the same sets every time depending on your conditions. 
```
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.vacuum_studio_slope_contact
            state: "on"
        sequence:
          - action: dreame_vacuum.vacuum_set_restricted_zone
            metadata: {}
            data:
              walls:
                - - -2700
                  - -1450
                  - 500
                  - -1450
                - - -1550
                  - -1450
                  - -1550
                  - -800
            target:
              entity_id: vacuum.d10_plus
        alias: Slope not in place
      - conditions:
          - condition: state
            entity_id: binary_sensor.vacuum_studio_slope_contact
            state: "off"
            alias: Slope in place
        sequence:
          - action: dreame_vacuum.vacuum_set_restricted_zone
            metadata: {}
            data:
              walls:
                - - -2700
                  - -1450
                  - -500
                  - -1450
                - - -1550
                  - -1450
                  - -1550
                  - -800
                - - -500
                  - -1450
                  - -500
                  - -1800
            target:
              entity_id: vacuum.d10_plus
    enabled: true
alias: Set unsafe paths for Vacuum
description: ""
icon: mdi:map-marker-path
```
