### ISSUE TITLE
Automation Dreame L40 Ultra

### ISSUE THREAD

**Issue by guihub78** [Tasshack/dreame-vacuum#1010]
Hello,

I just integrated Dreame Vacuum into Home Assistant for my L40 Ultra vacuum (I installed the latest Beta version).

I'm trying to create an automation to run it twice a week at 4:00 PM with the following settings:

Total rooms: 5
Specific room cleaning order
4 rooms with Vacuum + Mopping
1 room with Vacuum only

Each room has its own cleaning mode, humidity level, and suction power.

I'm using the dreame_vacuum.vacuum_set_custom_cleaning service, but the robot doesn't start on its own, so I have to add a delay and then use vacuum.start.

However, when the automation is triggered, the robot starts without installing the mop pads... I can't figure out why—maybe because vacuum.start only triggers vacuuming?

It's probably not possible, is it?

My YAML :

```
alias: Big Cleaning
description: Complet Cleaning
trigger:
  - platform: time
    at: "16:00:00"
condition:
  - condition: time
    weekday:
      - tue
      - fri
action:
  - service: dreame_vacuum.vacuum_set_custom_cleaning
    target:
      device_id:
        - a6c527190d579f81e159f3b3b584b87e
    data:
      segment_id:
        - 1
        - 8
        - 2 #rooms for only vacuum
        - 3
        - 4
      suction_level:
        - 3
        - 3
        - 3
        - 3
        - 3
      water_volume:
        - 2
        - 2
        - 1 # only vacuum
        - 3
        - 3
      cleaning_mode:
        - 2
        - 2
        - 0 # only vacuum
        - 2
        - 2
      repeats:
        - 1
        - 1
        - 1
        - 1
        - 1
  - delay: "00:00:05"
  - service: vacuum.start
    target:
      device_id: a6c527190d579f81e159f3b3b584b87e
mode: single
```

I found a way to make it start with the mop pads attached : 

```
- target:
      entity_id: select.aspirateur_l40_ultra_cleaning_mode
    data:
      option: sweeping_and_mopping
    action: select.select_option
```

However, when it reaches the room where I don’t want it to mop, it doesn’t lift the mop pads.
From what I understand, that’s because mop lifting isn’t supported through Home Assistant — it only works via the official Dreame app, right?

And I don’t think I can even set the water volume for each room.
When I run my automation like this, it only does Vacuum + Mop cleaning with humidity at 28 and Forte suction power.
I don’t feel like I can do exactly what I want :/

**Comment by guihub78** [comment]
> You also need to disable `cleangenius` and enable `customized_cleaning` settings for vacuum to use custom room cleaning settings.
> 
> > And I don’t think I can even set the water volume for each room.
> 
> You cannot use water_volume parameter for setting the wetness level. Instead you need to use wetness_level parameter which is not in the documentation yet.
> 
> ```
>   - service: dreame_vacuum.vacuum_set_custom_cleaning
>     target:
>       device_id:
>         - a6c527190d579f81e159f3b3b584b87e
>     data:
>       segment_id:
>         - 1
>         - 8
>         - 2
>         - 3
>         - 4
>       wetness_level:
>         - 20
>         - 28
>         - 1 # only vacuum
>         - 8
>         - 10
> ```

Perfect, I managed to do it using a script. However, I have to provide the water volume for it to work. If I run the script without this data, I get an error. So it works like this: 

`required key not provided @ data['water_volume']`

So here is my final script, which works perfectly:

```
alias: Grand nettoyage
mode: single
sequence:
  - service: dreame_vacuum.vacuum_set_custom_cleaning
    target:
      device_id: a6c527190d579f81e159f3b3b584b87e
    data:
      segment_id: [2, 1, 8, 3, 4]
      suction_level: [3, 3, 3, 3, 3]
      wetness_level: [1, 32, 32, 32, 32]
      water_volume: [1, 3, 3, 3, 3]
      cleaning_mode: [0, 2, 2, 2, 2]
      repeats: [1, 1, 1, 1, 1]
  - delay: "00:00:05"
  - service: vacuum.start
    target:
      device_id: a6c527190d579f81e159f3b3b584b87e
```

Do I have the right approach?
