### ISSUE TITLE
Script for 1 rooms

### ISSUE THREAD

**Issue by guihub78** [Tasshack/dreame-vacuum#1015]
Could you tell me why this script doesn’t clean only the room with ID 4?

```
alias: Nettoyer Salon - test
sequence:
  - data:
      segment_id: 4
      repeats: 1
      suction_level: 1
      water_volume: 1
      cleaning_mode: 0
      wetness_level: 1 
    action: dreame_vacuum.vacuum_set_custom_cleaning
    target:
      entity_id: vacuum.aspirateur_l40_ultra
  - data: {}
    action: vacuum.start
    target:
      entity_id: vacuum.aspirateur_l40_ultra
mode: single
```

My dreame_vacuum.vacuum_set_custom_cleaning set works because when I look at the entities, they do change correctly. 

But it doesn’t start at all with the parameters I asked for... and not even in the right room. Could you help me?

**Comment by guihub78** [comment]
Sorry for you help. 

Like that ? 

```
alias: Nettoyer Salon - test
sequence:
  - service: dreame_vacuum.vacuum_set_custom_cleaning
    data:
      entity_id: vacuum.aspirateur_l40_ultra
      segment_id: 4
      repeats: 1
      suction_level: 1
      water_volume: 1
      cleaning_mode: 0
      wetness_level: 1

  - service: dreame_vacuum.vacuum_clean_segment
    data:
      entity_id: vacuum.aspirateur_l40_ultra
      segments: [4]
mode: single
```

**Comment by guihub78** [comment]
This works fine for room 3 with vacuum only (no mop), but there’s no suction_level. Why?

I tried “1” or “quiet” but nothing works.

`alias: Nettoyage TEST
sequence:
  - action: dreame_vacuum.vacuum_clean_segment
    target:
      entity_id: vacuum.aspirateur_l40_ultra
    data:
      segments: 3
      suction_level: 1 or quiet
      repeats: 1
      water_volume: 1
mode: single
description: "" `

**Comment by guihub78** [comment]
Sorry for the spam—I think I’ve figured it out…

Can you tell me if this is how I should do it?

```
alias: Nettoyage TEST
sequence:
  - target:
      entity_id: switch.aspirateur_l40_ultra_customized_cleaning
    action: switch.turn_off
    data: {}
  - target:
      entity_id: select.aspirateur_l40_ultra_cleaning_mode
    data:
      option: sweeping
    action: select.select_option
  - target:
      entity_id: vacuum.aspirateur_l40_ultra
    data:
      segments:
        - 3
      suction_level: 1
      repeats: 1
      water_volume: 1
    action: dreame_vacuum.vacuum_clean_segment
mode: single
```
