### ISSUE TITLE
L10S Ultra Unable to Find Room with 2 Digit Room/Segment ID within Script

### ISSUE THREAD

**Issue by feerlessleadr** [Tasshack/dreame-vacuum#212]
**Describe the bug**
I have a total of 10 rooms in my downstairs map. I am able to call a room cleaning via a script for all of my rooms with the exception of my kitchen, which has a room/segment ID of '10'. When I try to call multiple rooms, including my kitchen, via a script, the Kitchen is always skipped. When I try to just clean the kitchen via a script, I get an error that the vacuum is unable to locate the room. 

When I look on the map, the kitchen is not highlighted when I run my script (like the other rooms are when I run their respective scripts). 

I am able to select the kitchen for room cleaning via the dashboard card manually, this problem seems to be limited to just a script. 

**To Reproduce**
Have a room ID with double digits. Create a script to clean the room with the double digit ID.

**Expected behavior**
The vacuum should clean the room as expected. 

**Screenshots**
<img width="960" alt="Daisy-HA-Error" src="https://github.com/Tasshack/dreame-vacuum/assets/288895/315212ce-5217-40ca-ba63-2bbbccadee71">

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: dreame.vacuum.r2228o
 - Firmware Version [e.g. 1156]: 4.3.6_3018
 - Home Assistant Version: Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest
 - Configuration Type [With or without map support]: With map support
 - Errors or warnings shown in the HA logs (if applicable): See above screenshot - no errors in the logbook.

Here is my script/YAML:

```
alias: Daisy Vacuum - Kitchen & Mud Room
sequence:
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      repeats: 1
      suction_level: 2
      segments:
        - 10
        - 5
    target:
      device_id: XXXXXXXX <-----Blanked this out, wasn't sure if this should be included or not
    alias: Clean Kitchen & Mudroom
mode: single
icon: mdi:robot-vacuum

```
