### ISSUE TITLE
cleaning_mode sweeping not available on r2251a

### ISSUE THREAD

**Issue by chrismelba** [Tasshack/dreame-vacuum#238]
First than you so much for this amazing repo.

**Describe the bug**
cleaning mode choices are only sweep/mop or mop on my dreame l10 prime which does have a lifting mop pad 

**To Reproduce**
On install the entity is created but no sweep mode is available 

**Expected behavior**
since my robot has a lifting mop I expect to be able to choose sweep only mode 

**Screenshots**

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: r2251a dreame l10 prime 
 - Firmware Version [e.g. 1156]: 4.3.3_1505
 - Home Assistant Version: 2023.10.1
 - Configuration Type [With or without map support]: with map support 
 - Errors or warnings shown in the HA logs (if applicable

**Comment by oleksandr-beley** [comment]
Confirm the same issue for r2216o

**Comment by chrismelba** [comment]
The l10 prime does have a self wash base though just FYI.

**Comment by digital-IMEI** [comment]
Hi,

without trying to hijack this issue. L10 Ultra is facing almost the same problem. Cleaning mode is completely unavailable. It has lifting moppads and cleaning base station.

Model number r2257o

If you need more info or testers, let me know!

**Comment by zanac** [comment]
If i try to call set_custom_cleaning with even the simple example yaml with dreambot L10S ultra i have:

Invocazione del servizio dreame_vacuum.vacuum_set_custom_cleaning non riuscita. Parameter count mismatch!

Using v2.0.0b6

**Comment by zanac** [comment]
here you are my sample... now the service has not error... but in the log of home assistant i get
Referenced devices vacuum.dreamebot_l10s_ultra are missing or not currently available

```
service: dreame_vacuum.vacuum_set_custom_cleaning
data:
  segment_id:
    - 7
    - 9
  suction_level:
    - 3
    - 3
  water_volume:
    - 2
    - 3
  cleaning_mode:
    - 2
    - 2
  repeats:
    - 2
    - 2
target:
  device_id: vacuum.dreamebot_l10s_ultra
```

**Comment by zanac** [comment]
Log is below... anyway my map is composed by 11 rooms, i want to make a custom button in home assistant that just clean room 7 and room 7 in a program... it is possible with that service?

2023-10-19 11:19:56.378 ERROR (MainThread) [custom_components.dreame_vacuum] Unable to call set_custom_cleaning: Parameter count mismatch! 2023-10-19 11:19:56.380 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Parameter count mismatch! 2023-10-19 11:19:56.382 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139732789998656] Error handling message: Parameter count mismatch! (unknown_error) Vanni Brutto from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/1 18.0.0.0 Safari/537.36)

**Comment by zanac** [comment]
> As i said before you cannot just set two of the segments of the whole map. You need to pass all settings for all 11 of your segments at once with this service. If you don't want set all room settings at once you need to use the segment select entities. It is not possible to disable some rooms from general cleaning, you need to use `vacuum_clean_segment` service for that.

Ok, but clean_segment is missing parameter "Cleaning Mode".... or a solution is a way to change first the cleaning mode and then use clean_segment....

**Comment by zanac** [comment]
This is a screenshot from "xiaomi app"... maybe if there is a way to change "cleaning mode" (first icon from this app) before to start clean_segment i have just solved my problem....

![image](https://github.com/Tasshack/dreame-vacuum/assets/21194919/85435de3-8967-48c8-9331-7d71eabac740)

**Comment by zanac** [comment]
O thanks! select.cleaning_mode is what i need! Great!

Last question (sorry, i'm newbie), i'm trying this yaml but it give error... i thank that "Pulizia con panno e aspirazione" is wrong value, maybe i need to use english value? If it's true what are option that i need to use for call select_option service?

```
service: select.select_option
data:
  option: "Pulizia con panno e aspirazione"
target:
  entity_id: select.dreamebot_l10s_ultra_cleaning_mode
```

**Comment by digital-IMEI** [comment]
> found looking source code! sweeping_and_mopping sweeping mopping
> 
> sorry for spam!

Could you share your solution? I’m trying to achieve the exact same thing. Documentation is pretty hard for newbies (at least for me).

**Comment by zanac** [comment]
> > found looking source code! sweeping_and_mopping sweeping mopping
> > sorry for spam!
> 
> Could you share your solution? I’m trying to achieve the exact same thing. Documentation is pretty hard for newbies (at least for me).

here you are a sample script that call select_option with "sweeping_and_mopping" before to select id of rooms to clean...

```
alias: DREAMBOT - Camere Aspira Lava 2X
sequence:
  - service: select.select_option
    data:
      option: sweeping_and_mopping
    target:
      entity_id: select.dreamebot_l10s_ultra_cleaning_mode
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      repeats: 2
      segments:
        - 4
        - 5
        - 6
        - 8
        - 9
        - 7
    target:
      entity_id: vacuum.dreamebot_l10s_ultra
mode: single

```
