### ISSUE TITLE
Start Auto-Empty is not available when Self-Clean is paused

### ISSUE THREAD

**Issue by mzakharo** [Tasshack/dreame-vacuum#324]
**Describe the bug**
Start Auto-Empty button is greyed out/unavailable while 'Self Clean' is paused. 
Start Auto-Empty button works in DreameHome app while 'Self Clean' is paused.

**To Reproduce**
Start Self Clean operation on L10S Ultra.  Pause it. Try to press 'auto empty' in HA, it will not work. But it will work through the official DreameHome app.

**Expected behavior**
Expected to engage Auto Empty sequence while Self Clean is paused.

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.r2228o
 - Firmware Version: 4.3.9_3031
 - Home Assistant Version:  2023.11.3
 - module version: [v2.0.0b9](https://github.com/Tasshack/dreame-vacuum/releases/tag/v2.0.0b9)
 - Configuration Type [With or without map support]: with map
 - Errors or warnings shown in the HA logs (if applicable):

**Comment by mzakharo** [comment]
Thanks. I am primarily looking to run auto empty when self clean is paused. This is my workaround for the unit to always run auto empty whenever it comes to refill water.

**Comment by mzakharo** [comment]
Thanks for the tip. Just FYI: there is a typo in your comment, it is `aiid` not `aaid` and there are no quotes around `action`.
```
- service: vacuum.send_command
    data:
      command: action
      params:
        did: "15.1"
        siid: 15
        aiid: 1
        in: []
```
