### ISSUE TITLE
First example of vacuum_clean_zone and vacuum_clean_spot gives error, but the other works.

### ISSUE THREAD

**Issue by skorpi0n** [Tasshack/dreame-vacuum#329]
**Describe the bug**
When following the first examples of vacuum_clean_zone and vacuum_clean_spot in https://github.com/Tasshack/dreame-vacuum/blob/master/docs/services.md I get the following error:
Failed to call service... ...None @ data['points'][0]

**To Reproduce**
Follow the example and modify it to my map:
```
service: dreame_vacuum.vacuum_clean_spot
data:
  points: 
    - -1447
    - -4935
target:
  entity_id: vacuum.dreamebot_d10s_plus
```

Changing to the style that the second example has, like this, works. (first datapoint has additional hyphen and 2nd datapoint has extra indentation)
```
service: dreame_vacuum.vacuum_clean_spot
data:
  points: 
    - - -1447
      - -4935
target:
  entity_id: vacuum.dreamebot_d10s_plus
```

This happens with v2.0.0b6 and v2.0.0b9 on Home Assistant 2023.10.1

Also, for the examples of vacuum_clean_spot, I think the headlines are wrong. They should have "spot" instead of "zone":
Clean selected zone > Clean selected spot
Clean multiple zones > Clean multiple spots
Clean selected zone two times > Clean selected spot two times
Clean first zone two times second zone three times > Clean first spot two times second spot three times
