### ISSUE TITLE
Select map in script not works correctly

### ISSUE THREAD

**Issue by andbad** [Tasshack/dreame-vacuum#351]
**Describe the bug**
I have living room in different floor (map) from others rooms.
So I get manually the vacuum and put in living room to clean it.
I made a script to select living room map and then start to clean this room.
After that, the initial map were been select.

**To Reproduce**
This is script:
```
script:
  duste_pulisci_sala:
    alias: Dust-e - Pulisci sala
    sequence:
      # I select living room map
      - service: dreame_vacuum.vacuum_select_map
        target:
          entity_id: vacuum.dust_e
        data:
          map_id: 37

      # Start vacuum to clean living room (only one room in this map)
      - service: dreame_vacuum.vacuum_clean_segment
        target:
          entity_id: vacuum.dust_e
        data:
          segments: 1

      # I wait until the cleaning is complete
      - delay:
          seconds: 15
      - wait_template: "{{ is_state('sensor.dust_e_status','standby') }}"

      # I select initial map for other rooms
      - service: dreame_vacuum.vacuum_select_map
        target:
          entity_id: vacuum.dust_e
        data:
          map_id: 2
    mode: single
    icon: mdi:robot-vacuum

```

**Expected behavior**
The script should load the living room map, start cleaning the room, and then reload the initial map.
When I start the script, the living room map is selected (select.dust_e_selected_map=living room map)
But when it start cleaning the living room, cleaning starts in room 1 of the initial map (the bathroom), as if I had not loaded the living room map. In this moment, the current map became initial map (select.dust_e_selected_map=initial map).
Of course the cleaning fail due to wrong room selected (cause the vacuum is in living room but the loaded map is initial map)

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: Dreame D10s
 - Firmware Version [e.g. 1156]: 4.1.8_1303
 - Home Assistant Version: 2023.12.4
 - Configuration Type [With or without map support]: With map support
 - Errors or warnings shown in the HA logs (if applicable): no error reported

**Comment by andbad** [comment]
> @andbad can you try to add a small delay on script after living room has been selected? Normally device requires a couple of seconds to load and send the new map data but integration handles this on memory like the app does so the selected map entity changes before map has been loaded to the device.

Thank you for your answer. I had tried to insert a delay, up to 120 seconds (after map select and before clean command) but the behavior didn't change: when it start to clean segment 1, automaticallly select map 2.

```
      - service: dreame_vacuum.vacuum_select_map
        target:
          entity_id: vacuum.dust_e
        data:
          map_id: 37

      - delay:
          seconds: 120

      - service: dreame_vacuum.vacuum_clean_segment
        target:
          entity_id: vacuum.dust_e
        data:
          segments: 1

```

By(t)e
