### ISSUE TITLE
Map selection is reverted after starting segment cleaning

### ISSUE THREAD

**Issue by xdrive** [Tasshack/dreame-vacuum#358]
**Describe the bug**
I have very same issue as reported in #351 . When selecting map with `dreame_vacuum.vacuum_select_map` and then starting robot with `dreame_vacuum.vacuum_clean_segment` the map selection is reverted to the one selected before the script was called. I have tried suggested workouround with delay of 10 seconds between map selection and starting the robot however it does not work in my case.

**To Reproduce**
1. robot has ground floor map selected
2. calling service `dreame_vacuum.vacuum_select_map` to set map to the first floor
3. having delay of 10 seconds 
4. I see that the selected map entity got successfully updated to the first floor. However in the native Dreame app I don't see any changes in regarding to selected map. Not sure if this is okay or not - just an observation
5. starting robot with `dreame_vacuum.vacuum_clean_segment` service
6. As soon as robot starts the map got reverted to the map which was selected before running the script.

If i select the map in the Dreame app and then start the robot with `dreame_vacuum.vacuum_clean_segment` service it works fine.

Here is the snippet of my automation:
```
action:
  - service: dreame_vacuum.vacuum_select_map
    data:
      map_id: 4
    target:
      device_id: XXXX
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      segments:
        - 2
        - 3
      suction_level: 2
      water_volume: 2
      repeats: 1
    target:
      device_id:XXXX
```

**Expected behavior**
After selecting a map and later starting the robot with `dreame_vacuum.vacuum_clean_segment` service it should use pre-selected map

**Additional Information (please complete the following information)**

Model Name: Dreame L10 Ultra dreame.vacuum.r2257o
Firmware Version [e.g. 1156]: 4.3.9_1609
Home Assistant Version: 2023.12.4
Configuration Type: With map support
Errors or warnings shown in the HA logs (if applicable): no error reported
