### ISSUE TITLE
Add error to vacuum entity status

### ISSUE THREAD

**Issue by DrBlokmeister** [Tasshack/dreame-vacuum#388]
I notice that the vacuum entity does not report an error when the device experiences an error, for example the mop pad comes off. The vacuum entity instead reports paused. This is not in line with other vacuum entities (as far as I know), the main example being the Xiaomi Roborock vacuums through the Xiaomi integration. These report an error state when any error occurs.

I'd like the vacuum entity to report an error state when any error occurs.

An example possibility to use this together with other vacuums is a notify automation like this:
```yaml
  - alias: '[home|vacuum]Notify Phone if Vacuum is in Error'
    id: home_vacuum_notify_phone_if_vacuum_is_in_error
    mode: parallel
    trigger:
      - platform: state
        entity_id: vacuum.argus
        to: "error"
        id: "Argus"
      - platform: state
        entity_id: vacuum.alfred
        to: "error"
        id: "Alfred"
      - platform: state
        entity_id: vacuum.moeke
        to: "error"
        id: "Moeke"
    action:
      - variables:
          vacuumentityid: "{{ trigger.entity_id }}"
      - service: camera.snapshot
        continue_on_error: true
        data:
          entity_id: "camera.{{ vacuumentityid[7:] }}_map"
          filename: "/config/www/tmp/snapshot_vacuum_error.jpg"
      - delay:
          seconds: 5
      - service: notify.mobile_app_blokmeistersphone
        continue_on_error: true
        data:
          title: "Error with {{ trigger.id }}"
          message: "Vacuum {{ trigger.id }} has state {{ trigger.to_state.state }}!"
          data:
            group: vacuum
            tag: vacuumerror
            icon_url: local/icons/robot-vacuum.png
            image: "/local/tmp/snapshot_vacuum_error.jpg"
```
