### ISSUE TITLE
Set the custom cleaning mode parameters on different scripts

### ISSUE THREAD

**Issue by calcioscacchi** [Tasshack/dreame-vacuum#409]
Hi there.
I enjoy that this feature was fixed with 2.0.012b!Thanks!

As I explained in another question, I need to set different custom cleaning modes on different scripts. 

For example, sometimes I want to sweep the flor, sometimes I need to sweeping and mopping. 

Trying to do this, I built a script which calls the "set the custom clenaing mode" service and I try to set the parameters:

![image](https://github.com/Tasshack/dreame-vacuum/assets/60674280/6175cba0-cd51-4983-8bda-bdc58aa09f81)

I found the values in the States page of Developer Tools menu:
![image](https://github.com/Tasshack/dreame-vacuum/assets/60674280/9fb105d3-7718-4402-8cec-704032527396)

Then I I try to run the script, this error happens:

 "invalid literal for int() with base 10: 'strong'"

Then I try with this:

```
service: dreame_vacuum.vacuum_set_custom_cleaning
metadata: {}
data:
  segment_id:
    - 7
  suction_level:
    - 1
  water_volume:
    - 1
  cleaning_mode:
    - 1
  repeats:
    - 1
target:
  entity_id: vacuum.battista
```

but it gives me this error:

"cannot access local variable 'segments' where it is not associated with a value".

Some hints?
