### ISSUE TITLE
Cleaning mode almost working: issue on cleaning_mode values

### ISSUE THREAD

**Issue by calcioscacchi** [Tasshack/dreame-vacuum#474]
**Describe the bug**
Setting values for "dreame_vacuum.vacuum_set_custom_cleaning" service is now working pretty well. I checked the Dreame APP and the settings are all updated. Thanks for that!

The only thing that is not working are the values for the "cleaning_mode" option: it accepts values 1 (only wasing) and 2 ( vacuum and washing). I supposed that "0" or "3" should be the value for vacuum only mode, but both are illegal values for this option.

**To Reproduce**
```
service: dreame_vacuum.vacuum_set_custom_cleaning
metadata: {}
data:
  segment_id:
    - 7
  suction_level:
    - 1
  water_volume:
    - 1
  cleaning_mode:
    - 0
  repeats:
    - 1
target:
  entity_id: vacuum.battista
```

**Expected behavior**
No errors occure when "0" or "3" is setted as value.

**Screenshots**
![image](https://github.com/Tasshack/dreame-vacuum/assets/60674280/4146a83e-869b-4e17-b7cd-18c6956d6fd7)
![image](https://github.com/Tasshack/dreame-vacuum/assets/60674280/aa31689f-ab39-4619-94bf-05d77630f676)

**Additional Information (please complete the following information)**
 - Model Name: [dreame.vacuum.r2251a]
 - Firmware Version [v2.0.0b13]:
 - Home Assistant Version: 2024.3
 - Configuration Type: [With map support]:
