### ISSUE TITLE
Cannot clean room with mop on Dreame L10 Prime

### ISSUE THREAD

**Issue by Maxinho96** [Tasshack/dreame-vacuum#483]
**Describe the bug**
I'm trying to use the `vacuum_clean_segment` service to mop a room with Dreame L10 Prime, but it starts with only suction activated.

**To Reproduce**
Configure the following `input_boolean` and launch it:
```yaml
- id: '1710794526817'
  alias: Mop kitchen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.mop_kitchen
    from:
    to: 'on'
  action:
  - service: dreame_vacuum.vacuum_clean_segment
    target:
      entity_id: vacuum.dreamebot_l10_prime
    data:
      segments: 3
      repeats: 3
      water_volume: 3
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.mop_kitchen
```

**Expected behavior**
The bot should mop the selected room, instead it starts with only vacuuming.

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.r2251a
 - Firmware Version: 4.3.3_1505
 - Home Assistant Version: 2024.3.1
 - Configuration Type: with map
