### ISSUE TITLE
Text glitch when robot is cleaning

### ISSUE THREAD

**Issue by r-jean-pierre** [Tasshack/dreame-vacuum#495]
**Describe the bug**
There is a strange text in the middle of the card which was not "like that" before the last update

**To Reproduce**
Just run a cleaning (with a Dreame D9)

**Expected behavior**
I don't remember what was written before (maybe time spent?, battery percentage?)

**Screenshots**
![2024_04_17_09_32_54_YAML_Dashboard_Home_Assistant](https://github.com/Tasshack/dreame-vacuum/assets/9727894/89a22ec6-968b-4f99-9411-d5d5e2cca300)

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: dreame.vacuum.p2009
 - Firmware Version [e.g. 1156]: 4.1.8_1132
 - Home Assistant Version:  2024.4.3
 - Configuration Type [With or without map support]: with map support
 - Errors or warnings shown in the HA logs (if applicable): none (?)

**Comment by r-jean-pierre** [comment]
> Can you at least share the card config?

Yes, sure:
```
- type: custom:vacuum-card
        entity: vacuum.dreame_vacuum_d9
        image: /local/D9.png
        stats:
          default:
            - attribute: main_brush_left
              unit: '%'
              subtitle: Main Brush left
            - attribute: side_brush_left
              unit: '%'
              subtitle: Side Brush left
            - attribute: filter_left
              unit: '%'
              subtitle: Filter left
            - attribute: cleaned_area
              unit: m²
              subtitle: Cleaned area
            - attribute: water_tank
              subtitle: Water box
          cleaning:
            - attribute: cleaning_time
              unit: percentage
              subtitle: Cleaning time
```
