### ISSUE TITLE
Sensor "Cleaning_history" should get the device_class timestamp

### ISSUE THREAD

**Issue by ChristophCaina** [Tasshack/dreame-vacuum#50]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It would be great, if the sensor "cleaning_history" would get the device_class: timestamp since it does provide a timestamp.
HA could then show the sensor like: "x minutes ago" - or "y days ago" ...

**Describe alternatives you've considered**
alternative solution would be, to create a template sensor and write the current value of cleaning history into the template.

**Additional context**
![grafik](https://user-images.githubusercontent.com/26391061/206394191-a8e5f683-4c7b-4d3b-8c7c-047abd9541fc.png)

Here's an example where I've used the template sensor to get the format:
![grafik](https://user-images.githubusercontent.com/26391061/206395230-ebc5e160-8f46-4bc1-ace4-186d53a8d57d.png)

Template:
```
  - sensor:
    - name: 'C-Q21 cleaning history timestamp'
      unique_id: 'c_q21_cleaning_history_timestamp'
      state: "{{ as_timestamp(states('sensor.c_q21_cleaning_history')) | timestamp_local }}"
      device_class: timestamp
```
