### ISSUE TITLE
Template Xiaomi Vacuum Map Card not working

### ISSUE THREAD

**Issue by FabioEight** [Tasshack/dreame-vacuum#59]
Hello, 

I followed all the instructions and configured my Z10 Pro in HA. I've also installed the Xiaomi Vacuum Map Card addon to use the lovelace card.
I copied the template code and set my variables but I'm unable to add the card to the view.
Here's my code:

```
{# ----------------- PROVIDE YOUR OWN ENTITY IDS HERE ----------------- #}
{% set camera_entity = "camera.xiaomi_cloud_map_extractor" %}
{% set vacuum_entity = "vacuum.dreame_bot_z10_pro" %}
{# ------------------- DO NOT CHANGE ANYTHING BELOW ------------------- #}
{% set attributes = states[camera_entity].attributes %}

type: custom:xiaomi-vacuum-map-card
vacuum_platform: default
entity: {{ vacuum_entity }}
map_source:
  camera: {{ camera_entity }}
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
    max_selections: 10
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: dreame_vacuum.vacuum_clean_zone
      service_data:
        entity_id: '[[entity_id]]'
        zone: '[[selection]]'
        repeats: '[[repeats]]'
  - template: vacuum_clean_segment
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: dreame_vacuum.vacuum_clean_segment
      service_data:
        entity_id: '[[entity_id]]'
        segments: '[[selection]]'
        repeats: '[[repeats]]'
    predefined_selections:
{%- for room_id in attributes.rooms | default([]) %}
{%- set room = attributes.rooms[room_id] %}
      - id: {{room_id}}
        outline:
          - - {{room["x0"]}}
            - {{room["y0"]}}
          - - {{room["x0"]}}
            - {{room["y1"]}}
          - - {{room["x1"]}}
            - {{room["y1"]}}
          - - {{room["x1"]}}
            - {{room["y0"]}}
{%- endfor %}
  - name: Clean Spot
    icon: mdi:map-marker-plus
    max_repeats: 3
    selection_type: MANUAL_POINT
    repeats_type: EXTERNAL
    service_call_schema:
      service: dreame_vacuum.vacuum_clean_spot
      service_data:
        entity_id: '[[entity_id]]'
        points: '[[selection]]'
        repeats: '[[repeats]]'
```
If I try to insert the card, I have a loading loop and I'm unable to save it. 
![image](https://user-images.githubusercontent.com/12196008/207905324-4e1f35f2-f8fb-4306-ac51-a03e1fec6de8.png)

Instead, if I edit the lovelace dashboard and save, I have the following error:

![image](https://user-images.githubusercontent.com/12196008/207905550-4b15e795-fdd0-463f-a278-777671d608e7.png)

`YAMLException: missed comma between flow collection entries (8:2) 5 | badges: [] 6 | cards: 7 | {# ----------------- PROVIDE YOUR ... 8 | {% set camera_entity = "camera.xi ... ------^ 9 | {% set vacuum_entity = "vacuum.dr ... 10 | {# ------------------- DO NOT CHA ...`

I tried verified the entity IDs and they are correct. Also tried to use a different map, including the ones generated by dreame-vacuum component but I'm unable to add the card.

 - Model Name dreame.vacuum.p2028
 - Firmware Version 1156 (rooted, no Valetudo)
 - Home Assistant Version: 2022.12.5
 - Configuration Type Automatic map support (cloud)
 - Errors or warnings shown in the HA logs (if applicable): /

Thank you!
