### ISSUE TITLE
vacuum_clean_segment How can I set different clean modes for each room?

### ISSUE THREAD

**Issue by martindybal** [Tasshack/dreame-vacuum#606]
I want to use `vacuum_clean_segment` to set the cleaning sequence. How can I set different modes for each room? 

Eg: I want to vacuuming & mopping room 3 and vacuuming before mopping in room 5.

```
service: dreame_vacuum.vacuum_clean_segment
data:
  segments:
    - 3
    - 5
  suction_level: "high"
  water_volume: 2
target:
  entity_id: vacuum.vacuum
```
