### ISSUE TITLE
Dreame X40 Pro Ultra does not work zonal assembly for mapping after sweeping

### ISSUE THREAD

**Issue by DivanX10** [Tasshack/dreame-vacuum#768]
**Describe the bug**

I send the vacuum cleaner to do zonal cleaning with such a team and it works properly
```
action: dreame_vacuum.vacuum_clean_segment
target:
  entity_id: vacuum.dreame_x40_pro_ultra
data:
  segments:
    - 1
    - 2
```

Zonal room cleaning does not work for mopping after sweeping 
1) If you choose dry cleaning (sweeping), then zonal room cleaning works properly
2) If you choose wet cleaning (mopping), then zonal room cleaning works properly
3) If you choose dry and wet cleaning (sweeping_and_mopping), then zonal room cleaning works properly
4) If you select wet after dry (mopping_after_sweeping), then zonal room cleaning does not work and cleaning is done only in one room

**To Reproduce**
Choose mopping after sweeping and select rooms

**Expected behavior**
After choosing mopping after sweeping and rooms, the vacuum cleaner must do the cleaning in the selected rooms

**Screenshots**
```
action: dreame_vacuum.vacuum_clean_segment
target:
  entity_id: vacuum.dreame_x40_pro_ultra
data:
  segments:
    - 1
    - 2
```

I have selected two rooms 1 and 2 with the command and first two rooms are displayed on the map
![2024-10-19_17-12-38](https://github.com/user-attachments/assets/a2fde515-6f7b-48dc-bd5f-d9b4b21f697b)

But when cleaning is started, only one room is displayed and cleaned
![2024-10-19_17-07-29](https://github.com/user-attachments/assets/a746f4fb-627f-4c64-9f98-b83e78ffd98c)

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.r2401 (Dreame X40 Pro Ultra)
 - Firmware Version: 4.3.9_1450
 - Home Assistant Version: 2024.10.3
 - Dreame Vacuum Version: v2.0.0b16
 - Configuration Type [With or without map support]: with card support
 - Errors or warnings shown in the HA logs (if applicable):
 

[home-assistant_dreame_vacuum_2024-10-19T16-53-16.183Z.log](https://github.com/user-attachments/files/17446719/home-assistant_dreame_vacuum_2024-10-19T16-53-16.183Z.log)
