### ISSUE TITLE
Dreame x40 Ultra - All custom cleaning option

### ISSUE THREAD

**Issue by telegrambeans** [Tasshack/dreame-vacuum#776]
First of all, thank you very much for the integration. 

My problem is that I can't give the dreame x 40 ultra all custom commands for cleaning. 

At the moment you can choose the rooms, the amount of water and the mode. What I'm still missing is the route. 

This creates a bug. 

I would like to be able to specify that it cleans deeply, for example, when vacuuming first and then wiping. 

Currently it does not pass on these parameters on the xiaomi-vacuum-card although I had previously chosen the option and resets it to the default. You cannot specify the route as an option in the command dreame_vacuum.vacuum_clean_segment. 

```
Example:

action: dreame_vacuum.vacuum_clean_segment
data:
  segments: "[3,2] "
  repeats: "[1] "
  suction_level: "[Standard]"
  water_volume: "[Moist] "
  cleaning_mode:  [Mopping after sweeping] 
  cleaning_route: [Deep] 
```

Thank you. Maybe you can improve that.
