### ISSUE TITLE
Issues using clean_xone service

### ISSUE THREAD

**Issue by calcioscacchi** [Tasshack/dreame-vacuum#873]
Hi there, 

I'm trying to use the combo "set_custom_cleaning" and "clean_zone" services.

```
sequence:
  - data:
      message: Attendere mentre configuro Battista per la pulizia della cucina
    action: notify.alexa_media_echo_soggiorno
  - metadata: {}
    data:
      suction_level:
        - 2
      water_volume:
        - 2
      cleaning_mode:
        - 2
      repeats:
        - 2
    target:
      entity_id: vacuum.battista
    action: dreame_vacuum.vacuum_set_custom_cleaning
  - data:
      message: Configurazione completata
    action: notify.alexa_media_echo_soggiorno
  - target:
      entity_id: vacuum.battista
    data:
      zone:
        - 897
        - -4259
        - 2868
        - 1022
    action: dreame_vacuum.vacuum_clean_zone
alias: Battista pulisci solo area cucina
mode: single
icon: mdi:robot-vacuum
description: ""

```

If I use this, the error 

`required key not provided @ data['segment_id']. Got None`

appears. 

Indeed, this error is quite clear, but I don't have a segment in my case, and I really need the "cleaning_mode"  option. 

Some hint about?
Thanks!
