### ISSUE TITLE
Dreame L10S Pro: vacuum_set_custom_cleaning action does nothing when triggered

### ISSUE THREAD

**Issue by prapador** [Tasshack/dreame-vacuum#874]
**Describe the bug**
I’m trying to use the set_custom_cleaning action, but when I run it, nothing happens. According to the documentation, the model is supported, but I haven't found a specific list of compatible devices with the action

**To Reproduce**  
My action configuration is:  

```yaml
action: dreame_vacuum.vacuum_set_custom_cleaning
data:
  segment_id:
    - 2
    - 8
    - 6
    - 1
    - 7
    - 4
    - 3
  suction_level:
    - 3
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
  water_volume:
    - 1
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
  repeats:
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
  cleaning_mode:
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
target:
  entity_id: vacuum.l10s_pro_gen_2
```

**Expected behavior**
The vacuum should start cleaning the specified segments with the configured settings.

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.l10spro
 - Firmware Version: 4.3.9_1134
 - Home Assistant Version: 2025.2.5
 - Configuration Type: Map Support
 - Errors or warnings shown in the HA logs (if applicable): Nothing
