### ISSUE TITLE
goto is not working (with Dreame L10s Pro)

### ISSUE THREAD

**Issue by badewanne1234** [Tasshack/dreame-vacuum#923]
I use the latest beta (V17) and the new goto service, however it does not work for my Dreame L10s Pro .
My previous solution was to clean a very small area, then fire "stop" as soon as the vacuum starts returing.

Previous solution (which is working):
```
action: dreame_vacuum.vacuum_clean_zone
data:
  zone:
    - - -3976
      - 5155
      - -3912
      - 5234
target:
  entity_id: vacuum.xxx
```

Using the goto service with coordinates from inside the above area throws an error "Coordinate is not inside the map", action is not executed.

```
action: dreame_vacuum.vacuum_goto
metadata: {}
data:
  x: -3950
  "y": 5200
target:
  entity_id: vacuum.xxx
```

It might be related to #737
